# Generated by Django 3.0.5 on 2020-05-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200521_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/pictures/profilepic.jpg', upload_to='profile_pictures'),
        ),
    ]
