# Generated by Django 2.2 on 2020-02-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://jibekjolu.us/wp-content/uploads/Image-Coming-Soon-Placeholder.png', max_length=500),
        ),
    ]
