# Generated by Django 3.0.5 on 2020-05-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='https://jibekjolu.us/wp-content/uploads/Image-Coming-Soon-Placeholder.png', upload_to=''),
        ),
    ]
