# Generated by Django 3.0.5 on 2020-05-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200519_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='https://media-cdn.tripadvisor.com/media/photo-s/0d/be/ad/22/new-city-centre-site.jpg', upload_to=''),
        ),
    ]
