# Generated by Django 3.0.5 on 2020-05-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20200519_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='img-comingsoon.jpg', upload_to='pictures'),
        ),
    ]
