# Generated by Django 3.0.5 on 2020-05-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20200519_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='img-comingsoon.jpg', max_length=50),
        ),
    ]
