# Generated by Django 3.0.5 on 2020-05-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20200520_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='media/pictures/img-comingsoon.jpg', upload_to='media/pictures'),
        ),
    ]
