# Generated by Django 3.0.5 on 2020-05-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20200521_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='pictures/img-comingsoon.jpg', upload_to='pictures'),
        ),
    ]
